### ISSUE TITLE
你好，我想问一下，这个是已经完成版的么

### ISSUE THREAD

**Issue by wangyuanbiubiubiu** [hlx1996/InfiniTAM#2]
我现在想用你的这个ros版的，我想问一下，你这个是已经完成版的么，然后我没看到有读原始图片的订阅信息，是输入深度图和pose么

**Comment by hlx1996** [comment]
您好，这个是完成版，不过主要是为了我们之前的项目，输入是深度图和pose。topic是下面两个，可以看launch文件。

```
    <remap from="~depth" to="/camera/depth/image_rect_raw" />
    <remap from="~pose"  to="/vins_estimator/camera_pose" />
```

**Comment by wangyuanbiubiubiu** [comment]
我想问一下,这个方便扩成加入rgb版本的么?我还想加入原图,这样就可以生成有颜色的地图,您对rgb这里的代码全部删除了么

**Comment by wangyuanbiubiubiu** [comment]
然后我现在的场景很大,是自动驾驶的场景,我想问一下,我可以通过修改什么参数能将三角形的个数减少一些呢?不然现在冗余的信息太多了

**Comment by hlx1996** [comment]
没有删除，大部分只是注释了，扩成rgb应该挺方便的，毕竟InfiniTAM本来就是支持RGB的。

wangyuanbiubiubiu <notifications@github.com> 于2019年8月2日周五 下午3:17写道：

**Comment by wangyuanbiubiubiu** [comment]
好的
